name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.1', '8.2']
    steps:
      - uses: actions/checkout@v1
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, gd, zip, intl
          ini-values: max_execution_time=600, memory_limit=-1
          coverage: xdebug
      - name: Validate composer.json
        run: |
          curl -sS https://getcomposer.org/installer | php -- --filename=composer
          composer validate
      - name: Install dependency
        run: |
          composer install
      - name: Check code standart
        run: |
          composer style
      - name: Analyze code
        run: |
          composer static-analyze
      - name: Run unit tests
        run: |
          composer unit
      - name: Run integration tests
        run: |
          composer integration
      - name: Run smoke tests
        run: |
          composer smoke           
